### ISSUE TITLE
"requires a peer of eslint@^6.0.0 but none is installed"

### ISSUE THREAD

**Issue by textbook** [CodeYourFuture/eslint-config-standard#4]
If you `npm init -y` a new NPM package in an empty directory then `npm install --save-dev eslint @codeyourfuture/eslint-config-standard` as suggested in the README, you see the following:

<pre><code>$ npm install --save-dev eslint @codeyourfuture/eslint-config-standard
npm notice created a lockfile as package-lock.json. You should commit this file.
<b>npm WARN @codeyourfuture/eslint-config-standard@2.0.1 requires a peer of eslint@^6.0.0 but none is installed. You must install peer dependencies yourself.</b>
npm WARN cyf-eslint@1.0.0 No description
npm WARN cyf-eslint@1.0.0 No repository field.

+ @codeyourfuture/eslint-config-standard@2.0.1
+ eslint@7.5.0
added 108 packages from 64 contributors and audited 108 packages in 2.002s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities</code></pre>

This is because the peer dependency is specified as: 
```json
  "peerDependencies": {
    "eslint": "^6.0.0"
  }
```
which (as illustrated by e.g. https://semver.npmjs.com/) covers all 6.x versions of ESLint but not the current 7.x versions. The plugin still works with [ESLint 7](https://eslint.org/blog/2020/05/eslint-v7.0.0-released), so the peer dependency should be widened.

**Comment by ghost** [comment]
Hello! I'd love to work on this if it's okay :)

**Comment by textbook** [comment]
@Aichi-Chang go for it, let me know if you need any guidance 🙂
